"""add column soft delete

Revision ID: 43490789b376
Revises: 603b3829371a
Create Date: 2025-10-04 21:28:04.147622

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "43490789b376"
down_revision: Union[str, Sequence[str], None] = "603b3829371a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "documents", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "evaluations",
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("evaluations", "deleted_at")
    op.drop_column("documents", "deleted_at")
    # ### end Alembic commands ###
